"""
Portfolio Schemas

Pydantic models for portfolio operations.
"""

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field

from app.schemas.design import DesignConfig


class PortfolioBlueprint(BaseModel):
    """
    Portfolio structure blueprint generated by AI.
    
    Defines page structure, section priority, tone, and content length.
    No HTML/CSS - structure only.
    """
    
    pages: List[str] = Field(
        default_factory=lambda: ["home", "about", "experience", "projects", "contact"],
        description="List of pages to include"
    )
    section_priority: Dict[str, str] = Field(
        default_factory=dict,
        description="Priority levels (high/medium/low) for each section"
    )
    tone: Literal["professional", "creative", "technical", "executive"] = Field(
        default="professional",
        description="Overall content tone"
    )
    content_length: Literal["concise", "standard", "detailed"] = Field(
        default="standard",
        description="Content verbosity level"
    )


class PortfolioCreate(BaseModel):
    """Request to create a new portfolio."""
    
    resume_id: UUID
    name: Optional[str] = None


class PortfolioContent(BaseModel):
    """Generated portfolio content mapped to sections."""
    
    hero: Dict[str, Any] = Field(default_factory=dict)
    about: Dict[str, Any] = Field(default_factory=dict)
    experience: List[Dict[str, Any]] = Field(default_factory=list)
    projects: List[Dict[str, Any]] = Field(default_factory=list)
    skills: List[str] = Field(default_factory=list)
    education: List[Dict[str, Any]] = Field(default_factory=list)
    achievements: List[str] = Field(default_factory=list)
    contact: Dict[str, Any] = Field(default_factory=dict)


class PortfolioResponse(BaseModel):
    """Full portfolio response."""
    
    id: UUID
    name: str
    status: str
    blueprint: Optional[PortfolioBlueprint] = None
    content: Optional[PortfolioContent] = None
    design_config: Optional[DesignConfig] = None
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True


class PortfolioVersionResponse(BaseModel):
    """Portfolio version history entry."""
    
    id: UUID
    version_number: int
    created_at: datetime
    
    class Config:
        from_attributes = True


class SectionEditRequest(BaseModel):
    """
    Request for AI-assisted section editing.
    
    The AI operates ONLY within the specified section scope.
    It cannot modify other sections or invent new information.
    """
    
    section_type: Literal[
        "hero", "about", "experience", "projects", 
        "skills", "education", "achievements", "contact"
    ]
    current_content: Dict[str, Any]
    instruction: str = Field(
        ...,
        min_length=10,
        max_length=500,
        description="User instruction for editing this section"
    )


class SectionEditResponse(BaseModel):
    """Response from section edit operation."""
    
    section_type: str
    updated_content: Dict[str, Any]
    changes_made: List[str] = Field(
        default_factory=list,
        description="Summary of changes applied"
    )


class ATSCheckResult(BaseModel):
    """ATS compatibility check result."""
    
    score: int = Field(..., ge=0, le=100, description="Overall ATS score")
    keyword_coverage: float = Field(..., ge=0, le=1)
    bullet_clarity: float = Field(..., ge=0, le=1)
    readability_score: float = Field(..., ge=0, le=1)
    section_completeness: Dict[str, bool] = Field(default_factory=dict)
    suggestions: List[str] = Field(default_factory=list)
    passed: bool = Field(default=False)


class PublishRequest(BaseModel):
    """Request to publish a portfolio."""
    
    subdomain: str = Field(
        ...,
        min_length=3,
        max_length=63,
        pattern="^[a-z0-9][a-z0-9-]*[a-z0-9]$",
        description="Subdomain for the published site"
    )
    custom_domain: Optional[str] = None


class PublishResponse(BaseModel):
    """Response after publishing a portfolio."""
    
    portfolio_id: UUID
    subdomain: str
    url: str
    custom_domain: Optional[str] = None
    published_at: datetime
